{
 "title": "Netology",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m]))* 100)"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\",mountpoint!=\"/boot\",job=\"node\"} ",
     "legendFormat": "{{mountpoint}} "
    }
   ]
  },
  {
   "title": "CPU LA 1/5/15 (1 core)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPU LA  1" },
    { "expr": "node_load5", "legendFormat": "CPU LA  5" },
    { "expr": "node_load15", "legendFormat": "CPU LA  15" }
   ]
  },
  {
   "title": "Memory Free ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes/1024/1024",
     "legendFormat": "Memory Free "
    }
   ]
  }
 ]
}