# my global config
global:
  #scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration Для себя дополнительно настроил
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
    #  - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "rules.yml"
    - "alert.rules"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:


########### JOB prometheus ############################
#  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
#
#    # metrics_path defaults to '/metrics'
#    # scheme defaults to 'http'.
#
#    #9090 - prometheus.
#    #9091 - prometheus gateway
    static_configs:
    - targets: ['localhost:9090']
####################################

########### JOB prometheus Gateway ############################
  - job_name: 'prometheus_gate'
    static_configs:
    - targets: ['localhost:9091']
####################################

########### Local Node Exporter###############
  - job_name: 'node'
    static_configs:
    - targets:
      - localhost:9100
#########################################
