global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'security'
    scrape_interval: 5s
    static_configs:
      - targets: ['security:3000']


  - job_name: 'uploader'
    scrape_interval: 5s
    static_configs:
      - targets: ['uploader:3000']

  - job_name: 'storage'
    scrape_interval: 5s
    static_configs:
      - targets: ['gateway:8080']



